"""Shared helpers for the research agents."""

from metrics import metrics
from protocol import cosine_similarity


def _get_mode(state: dict) -> str:
    """Get communication mode from state."""
    return state.get("mode", "text")


def _extract_hidden_state(response) -> dict | None:
    """Extract hidden-state metadata from a local Transformers response."""
    metadata = getattr(response, "response_metadata", None) or {}
    payload = metadata.get("hidden_state_payload")
    if isinstance(payload, dict):
        return payload
    return None


def _hidden_state_summary(payload: dict | None) -> dict:
    """Return compact metadata without copying the full vector into prompt text."""
    if not payload:
        return {"available": False}
    return {
        "available": True,
        "kind": payload.get("kind"),
        "model": payload.get("model"),
        "layer": payload.get("layer"),
        "pooling": payload.get("pooling"),
        "dims": payload.get("dims"),
        "norm": payload.get("norm"),
        "source_text_hash": payload.get("source_text_hash"),
    }


def _record_hidden_state_received(agent: str, payload: dict | None):
    """Record that an agent received a non-text hidden-state payload."""
    if not payload:
        return
    metrics.increment(f"hidden_state_received_{agent}")
    metrics.increment("hidden_state_vector_dims_received", int(payload.get("dims", 0)))


def _hidden_state_vector(payload: dict | None) -> list[float] | None:
    """Return a serialized hidden vector if present."""
    if not isinstance(payload, dict):
        return None
    vector = payload.get("vector")
    if not isinstance(vector, list):
        return None
    return vector


def _hidden_state_alignment(left: dict | None, right: dict | None) -> float | None:
    """Compare two hidden-state payloads generated by the same local model."""
    left_vector = _hidden_state_vector(left)
    right_vector = _hidden_state_vector(right)
    if not left_vector or not right_vector:
        return None
    return round(float(cosine_similarity(left_vector, right_vector)), 4)


def _hidden_guidance_from_packets(
    packets: list[dict],
    *,
    candidate_count: int,
    top_k: int,
    candidate_type: str = "context packets",
) -> dict:
    """Summarize how hidden-state ranking affected downstream context."""
    hidden_scores = []
    for packet in packets:
        components = packet.get("score_components", {}) or {}
        score = components.get("hidden_state")
        if score is not None:
            hidden_scores.append(float(score))
    if not hidden_scores:
        return {
            "used": False,
            "candidate_type": candidate_type,
            "candidate_packets": candidate_count,
            "selected_packets": len(packets),
        }
    return {
        "used": True,
        "candidate_type": candidate_type,
        "candidate_packets": candidate_count,
        "selected_packets": len(packets),
        "context_top_k": top_k,
        "skipped_packets": max(candidate_count - len(packets), 0),
        "selected_doc_keys": [packet.get("doc_key") for packet in packets],
        "avg_hidden_score": round(sum(hidden_scores) / len(hidden_scores), 4),
        "top_hidden_score": round(max(hidden_scores), 4),
    }


def _hidden_guidance_prompt(hidden_guidance: dict | None) -> str:
    """Render hidden-state guidance as compact prompt metadata."""
    if not hidden_guidance or not hidden_guidance.get("used"):
        return ""
    return (
        "\nHidden-state routing: planner/researcher intent alignment selected "
        f"{hidden_guidance.get('selected_packets')} of "
        f"{hidden_guidance.get('candidate_packets')} "
        f"{hidden_guidance.get('candidate_type', 'context packets')}; "
        f"selected_doc_keys={hidden_guidance.get('selected_doc_keys')}; "
        f"avg_hidden_score={hidden_guidance.get('avg_hidden_score')}."
    )


def _normalize_sub_queries(query: str, sub_queries: list) -> list[str]:
    """Ensure fan-out has three distinct research candidates."""
    normalized = []
    seen = set()
    for item in sub_queries or []:
        text = str(item).strip()
        if not text or len(text) < 8 or text in seen:
            continue
        seen.add(text)
        normalized.append(text)
        if len(normalized) == 3:
            return normalized

    fallback_aspects = [
        f"{query} 的核心概念和机制",
        f"{query} 的实现方式和关键组件",
        f"{query} 的性能、可靠性和应用场景",
    ]
    for text in fallback_aspects:
        if text in seen:
            continue
        normalized.append(text)
        if len(normalized) == 3:
            break
    return normalized
