#!/usr/bin/env bash

_statebus_contest_restore_shell_options() {
  if [[ "${_STATEBUS_CONTEST_HAD_ERREXIT:-0}" == "1" ]]; then
    set -o errexit
  else
    set +o errexit
  fi
  if [[ "${_STATEBUS_CONTEST_HAD_NOUNSET:-0}" == "1" ]]; then
    set -o nounset
  else
    set +o nounset
  fi
  if [[ "${_STATEBUS_CONTEST_HAD_PIPEFAIL:-0}" == "1" ]]; then
    set -o pipefail
  else
    set +o pipefail
  fi
}

_statebus_activate_contest_rebuild_main() {
  set -euo pipefail

  local script_dir repo_root profile_file
  script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  repo_root="$(cd "${script_dir}/.." && pwd)"

  if [[ ! -f "${script_dir}/activate_statebus_host.sh" ]]; then
    echo "[statebus-contest] missing host activation script" >&2
    return 1
  fi

  # shellcheck disable=SC1090
  source "${script_dir}/activate_statebus_host.sh"

  export STATEBUS_CONTEST_PROFILE="contest-rebuild-20260722"
  export STATEBUS_CONTEST_PROFILE_VERSION="1"
  export STATEBUS_CONTEST_PROFILE_PHASE="${STATEBUS_CONTEST_PROFILE_PHASE:-prepare}"
  export STATEBUS_CONTEST_PROJECT_ROOT="$repo_root"

  profile_file="${STATEBUS_CONTEST_ENV_FILE:-${script_dir}/statebus_contest_rebuild.env.local}"
  export STATEBUS_CONTEST_ENV_FILE="$profile_file"
  if [[ -f "$profile_file" ]]; then
    # shellcheck disable=SC1090
    source "$profile_file"
  fi

  export STATEBUS_CACHES_DIR="${STATEBUS_CACHES_DIR:-$STATEBUS_HOME/caches}"
  export STATEBUS_CONTEST_DATA_ROOT="${STATEBUS_CONTEST_DATA_ROOT:-$STATEBUS_WORKDIR/contest-rebuild/data}"
  export STATEBUS_CONTEST_RUN_ROOT="${STATEBUS_CONTEST_RUN_ROOT:-$STATEBUS_RUNS_DIR/contest-rebuild-v1}"
  export STATEBUS_CONTEST_LOG_ROOT="${STATEBUS_CONTEST_LOG_ROOT:-$STATEBUS_LOGS_DIR/contest-rebuild-v1}"
  export STATEBUS_FILING_DOWNLOAD_ROOT="${STATEBUS_FILING_DOWNLOAD_ROOT:-$STATEBUS_CACHES_DIR/contest-rebuild/public-filings/raw}"
  export STATEBUS_FILING_CANONICAL_ROOT="${STATEBUS_FILING_CANONICAL_ROOT:-$STATEBUS_CONTEST_DATA_ROOT/public-filings/canonical}"
  export STATEBUS_FILING_PRIVATE_GOLD_ROOT="${STATEBUS_FILING_PRIVATE_GOLD_ROOT:-$STATEBUS_WORKDIR/contest-rebuild/gold-private}"

  export STATEBUS_CONTEST_LLM_CONFIG_FILE="${STATEBUS_CONTEST_LLM_CONFIG_FILE:-${script_dir}/statebus_llm.contest_rebuild.yaml}"
  export STATEBUS_LLM_CONFIG_FILE="$STATEBUS_CONTEST_LLM_CONFIG_FILE"
  export STATEBUS_LLM_MODE="local_vllm"

  export STATEBUS_CONTEST_VLLM_MODEL_PATH="${STATEBUS_CONTEST_VLLM_MODEL_PATH:-/data/models/Qwen3-32B}"
  export STATEBUS_CONTEST_VLLM_TOKENIZER_PATH="${STATEBUS_CONTEST_VLLM_TOKENIZER_PATH:-$STATEBUS_CONTEST_VLLM_MODEL_PATH}"
  export STATEBUS_CONTEST_VLLM_ENV_PREFIX="${STATEBUS_CONTEST_VLLM_ENV_PREFIX:-$STATEBUS_HOME/conda-envs/vllm-qwen-cu121}"
  export STATEBUS_CONTEST_VLLM_HOST="${STATEBUS_CONTEST_VLLM_HOST:-127.0.0.1}"
  export STATEBUS_CONTEST_VLLM_PORT="${STATEBUS_CONTEST_VLLM_PORT:-53334}"
  export STATEBUS_CONTEST_VLLM_CUDA_VISIBLE_DEVICES="${STATEBUS_CONTEST_VLLM_CUDA_VISIBLE_DEVICES:-1}"
  export STATEBUS_CONTEST_VLLM_TENSOR_PARALLEL_SIZE="${STATEBUS_CONTEST_VLLM_TENSOR_PARALLEL_SIZE:-1}"
  export STATEBUS_CONTEST_VLLM_MAX_MODEL_LEN="${STATEBUS_CONTEST_VLLM_MAX_MODEL_LEN:-8192}"
  export STATEBUS_CONTEST_VLLM_MAX_NUM_SEQS="${STATEBUS_CONTEST_VLLM_MAX_NUM_SEQS:-1}"
  export STATEBUS_CONTEST_VLLM_MAX_NUM_BATCHED_TOKENS="${STATEBUS_CONTEST_VLLM_MAX_NUM_BATCHED_TOKENS:-8192}"
  export STATEBUS_CONTEST_VLLM_GPU_MEMORY_UTILIZATION="${STATEBUS_CONTEST_VLLM_GPU_MEMORY_UTILIZATION:-0.82}"
  export STATEBUS_CONTEST_VLLM_DTYPE="${STATEBUS_CONTEST_VLLM_DTYPE:-bfloat16}"
  export STATEBUS_CONTEST_VLLM_ENFORCE_EAGER="${STATEBUS_CONTEST_VLLM_ENFORCE_EAGER:-1}"
  export STATEBUS_CONTEST_VLLM_EXPECTED_VERSION="${STATEBUS_CONTEST_VLLM_EXPECTED_VERSION:-0.9.2}"
  export STATEBUS_CONTEST_VLLM_USE_V1="${STATEBUS_CONTEST_VLLM_USE_V1:-0}"
  export STATEBUS_CONTEST_VLLM_START_SCRIPT="${STATEBUS_CONTEST_VLLM_START_SCRIPT:-$repo_root/scripts/start_vllm_qwen3_32b_latent.sh}"
  export STATEBUS_CONTEST_VLLM_MAX_LOGPROBS="${STATEBUS_CONTEST_VLLM_MAX_LOGPROBS:-20}"
  export STATEBUS_CONTEST_VLLM_ENABLE_REQUEST_ID_HEADERS="${STATEBUS_CONTEST_VLLM_ENABLE_REQUEST_ID_HEADERS:-1}"
  export STATEBUS_CONTEST_LATENT_API_TOKEN_FILE="${STATEBUS_CONTEST_LATENT_API_TOKEN_FILE:-$STATEBUS_WORKDIR/latent_api.token}"
  export STATEBUS_CONTEST_VLLM_NUM_GPU_BLOCKS_OVERRIDE="${STATEBUS_CONTEST_VLLM_NUM_GPU_BLOCKS_OVERRIDE:-}"
  export STATEBUS_CONTEST_VLLM_CPU_OFFLOAD_GB="${STATEBUS_CONTEST_VLLM_CPU_OFFLOAD_GB:-}"
  export STATEBUS_CONTEST_VLLM_KV_CACHE_DTYPE="${STATEBUS_CONTEST_VLLM_KV_CACHE_DTYPE:-}"

  export STATEBUS_VLLM_MODEL_PATH="$STATEBUS_CONTEST_VLLM_MODEL_PATH"
  export STATEBUS_VLLM_TOKENIZER_PATH="$STATEBUS_CONTEST_VLLM_TOKENIZER_PATH"
  export STATEBUS_VLLM_ENV_PREFIX="$STATEBUS_CONTEST_VLLM_ENV_PREFIX"
  export STATEBUS_VLLM_SERVED_MODEL_NAME="qwen3-32b"
  export STATEBUS_LOCAL_VLLM_MODEL="qwen3-32b"
  export STATEBUS_VLLM_HOST="$STATEBUS_CONTEST_VLLM_HOST"
  export STATEBUS_VLLM_PORT="$STATEBUS_CONTEST_VLLM_PORT"
  export STATEBUS_LOCAL_VLLM_PORT="$STATEBUS_CONTEST_VLLM_PORT"
  export STATEBUS_LOCAL_VLLM_BASE_URL="http://${STATEBUS_CONTEST_VLLM_HOST}:${STATEBUS_CONTEST_VLLM_PORT}/v1"
  export STATEBUS_LOCAL_VLLM_HEALTH_URL="http://${STATEBUS_CONTEST_VLLM_HOST}:${STATEBUS_CONTEST_VLLM_PORT}/health"
  export STATEBUS_VLLM_METRICS_URL="http://${STATEBUS_CONTEST_VLLM_HOST}:${STATEBUS_CONTEST_VLLM_PORT}/metrics"
  export STATEBUS_VLLM_START_SCRIPT="$STATEBUS_CONTEST_VLLM_START_SCRIPT"
  export STATEBUS_VLLM_CUDA_VISIBLE_DEVICES="$STATEBUS_CONTEST_VLLM_CUDA_VISIBLE_DEVICES"
  export STATEBUS_VLLM_TENSOR_PARALLEL_SIZE="$STATEBUS_CONTEST_VLLM_TENSOR_PARALLEL_SIZE"
  export STATEBUS_VLLM_MAX_MODEL_LEN="$STATEBUS_CONTEST_VLLM_MAX_MODEL_LEN"
  export STATEBUS_VLLM_MAX_NUM_SEQS="$STATEBUS_CONTEST_VLLM_MAX_NUM_SEQS"
  export STATEBUS_VLLM_MAX_NUM_BATCHED_TOKENS="$STATEBUS_CONTEST_VLLM_MAX_NUM_BATCHED_TOKENS"
  export STATEBUS_VLLM_GPU_MEMORY_UTILIZATION="$STATEBUS_CONTEST_VLLM_GPU_MEMORY_UTILIZATION"
  export STATEBUS_VLLM_DTYPE="$STATEBUS_CONTEST_VLLM_DTYPE"
  export STATEBUS_VLLM_ENFORCE_EAGER="$STATEBUS_CONTEST_VLLM_ENFORCE_EAGER"
  export STATEBUS_VLLM_EXPECTED_VERSION="$STATEBUS_CONTEST_VLLM_EXPECTED_VERSION"
  export STATEBUS_VLLM_MAX_LOGPROBS="$STATEBUS_CONTEST_VLLM_MAX_LOGPROBS"
  export STATEBUS_VLLM_ENABLE_REQUEST_ID_HEADERS="$STATEBUS_CONTEST_VLLM_ENABLE_REQUEST_ID_HEADERS"
  export STATEBUS_VLLM_NUM_GPU_BLOCKS_OVERRIDE="$STATEBUS_CONTEST_VLLM_NUM_GPU_BLOCKS_OVERRIDE"
  export STATEBUS_VLLM_CPU_OFFLOAD_GB="$STATEBUS_CONTEST_VLLM_CPU_OFFLOAD_GB"
  export STATEBUS_VLLM_KV_CACHE_DTYPE="$STATEBUS_CONTEST_VLLM_KV_CACHE_DTYPE"
  export STATEBUS_VLLM_EXPORT_PREFIX_COUNTERS="1"
  export STATEBUS_VLLM_SERVICE_NAME="statebus-vllm-qwen3-32b-allcap"
  export STATEBUS_LATENT_API_TOKEN_FILE="$STATEBUS_CONTEST_LATENT_API_TOKEN_FILE"
  export STATEBUS_LATENT_ALIGNMENT="soft_token_topk_v1"
  export STATEBUS_LATENT_ALIGNMENT_DIAGNOSTICS="true"
  export VLLM_USE_V1="$STATEBUS_CONTEST_VLLM_USE_V1"
  export VLLM_NO_USAGE_STATS="1"
  export CUDA_VISIBLE_DEVICES="$STATEBUS_CONTEST_VLLM_CUDA_VISIBLE_DEVICES"

  export STATEBUS_VLLM_METRICS_TIMEOUT_S="${STATEBUS_VLLM_METRICS_TIMEOUT_S:-5}"
  export STATEBUS_VLLM_METRICS_SCHEMA_STATUS="${STATEBUS_VLLM_METRICS_SCHEMA_STATUS:-pending_live_check}"
  export STATEBUS_VLLM_METRIC_QUERY_NAMES="${STATEBUS_VLLM_METRIC_QUERY_NAMES:-vllm:prefix_cache_queries_total,vllm_prefix_cache_queries_total,vllm:gpu_prefix_cache_queries_total,vllm_gpu_prefix_cache_queries_total}"
  export STATEBUS_VLLM_METRIC_HIT_NAMES="${STATEBUS_VLLM_METRIC_HIT_NAMES:-vllm:prefix_cache_hits_total,vllm_prefix_cache_hits_total,vllm:gpu_prefix_cache_hits_total,vllm_gpu_prefix_cache_hits_total}"

  export STATEBUS_TOP_LOGPROBS_PROBE_TOP_K="${STATEBUS_TOP_LOGPROBS_PROBE_TOP_K:-5}"
  export STATEBUS_TOP_LOGPROBS_PROBE_MAX_TOKENS="${STATEBUS_TOP_LOGPROBS_PROBE_MAX_TOKENS:-1}"
  export STATEBUS_TOP_LOGPROBS_CAPABILITY_STATUS="${STATEBUS_TOP_LOGPROBS_CAPABILITY_STATUS:-pending_live_check}"

  export STATEBUS_FILING_SOURCE_ID="${STATEBUS_FILING_SOURCE_ID:-xbrl_international_filings}"
  export STATEBUS_FILING_SOURCE_BASE_URL="${STATEBUS_FILING_SOURCE_BASE_URL:-https://filings.xbrl.org}"
  export STATEBUS_FILING_HTTP_TIMEOUT_S="${STATEBUS_FILING_HTTP_TIMEOUT_S:-30}"
  export STATEBUS_FILING_RATE_LIMIT_S="${STATEBUS_FILING_RATE_LIMIT_S:-1.0}"
  export STATEBUS_FILING_MAX_ARCHIVE_BYTES="${STATEBUS_FILING_MAX_ARCHIVE_BYTES:-536870912}"

  export STATEBUS_CONTEST_PREFIX_POLICY="${STATEBUS_CONTEST_PREFIX_POLICY:-off}"
  export STATEBUS_CONTEST_LOGIT_POLICY="${STATEBUS_CONTEST_LOGIT_POLICY:-off}"
  export STATEBUS_CONTEST_PREFIX_FEEDBACK_ADAPTIVE="${STATEBUS_CONTEST_PREFIX_FEEDBACK_ADAPTIVE:-0}"
  export STATEBUS_PREFIX_POLICY="$STATEBUS_CONTEST_PREFIX_POLICY"
  export STATEBUS_PREFIX_ALIGNMENT_MODE="independent"
  export STATEBUS_PREFIX_LAYOUT_VERSION="${STATEBUS_PREFIX_LAYOUT_VERSION:-v2}"
  export STATEBUS_PREFIX_REQUIRE_EXCLUSIVE_METRICS="${STATEBUS_PREFIX_REQUIRE_EXCLUSIVE_METRICS:-true}"
  export STATEBUS_PREFIX_FEEDBACK_ADAPTIVE="$STATEBUS_CONTEST_PREFIX_FEEDBACK_ADAPTIVE"
  export STATEBUS_PREFIX_CACHE_NAMESPACE="${STATEBUS_PREFIX_CACHE_NAMESPACE:-}"
  export STATEBUS_PREFIX_CACHE_EPOCH="${STATEBUS_PREFIX_CACHE_EPOCH:-}"
  export STATEBUS_LOGIT_POLICY="$STATEBUS_CONTEST_LOGIT_POLICY"
  export STATEBUS_LOGIT_DECISION_TYPE="${STATEBUS_LOGIT_DECISION_TYPE:-executor_tool_recipe_choice_v1}"
  export STATEBUS_LOGIT_MAX_ACTIONS="${STATEBUS_LOGIT_MAX_ACTIONS:-1}"
  export STATEBUS_LOGIT_LEASE_MS="${STATEBUS_LOGIT_LEASE_MS:-30000}"
  export STATEBUS_LOGIT_STATE_POOL_MODE="${STATEBUS_LOGIT_STATE_POOL_MODE:-shared_memory}"

  # Latent/prompt-embedding/KV handoff is permanently excluded from this profile.
  export STATEBUS_LATENT_MODE="off"
  export STATEBUS_LATENT_HANDOFF_MODE="off"
  export STATEBUS_LATENT_PROMPT_EMBEDS_ENABLED="false"

  export STATEBUS_FORMAL_REQUEST_MODE="${STATEBUS_FORMAL_REQUEST_MODE:-serialized}"
  export STATEBUS_FORMAL_REQUEST_CONCURRENCY="${STATEBUS_FORMAL_REQUEST_CONCURRENCY:-1}"
  export STATEBUS_CONTEST_ALLOW_METRICS_CHECK="${STATEBUS_CONTEST_ALLOW_METRICS_CHECK:-0}"
  export STATEBUS_CONTEST_ALLOW_TOP_LOGPROBS_PROBE="${STATEBUS_CONTEST_ALLOW_TOP_LOGPROBS_PROBE:-0}"
  export STATEBUS_CONTEST_ALLOW_FILING_DOWNLOAD="${STATEBUS_CONTEST_ALLOW_FILING_DOWNLOAD:-0}"
  export STATEBUS_CONTEST_ALLOW_FORMAL_EXPERIMENTS="${STATEBUS_CONTEST_ALLOW_FORMAL_EXPERIMENTS:-0}"
  export STATEBUS_CONTEST_ALLOW_COLD_CACHE="${STATEBUS_CONTEST_ALLOW_COLD_CACHE:-0}"
  export STATEBUS_CONTEST_ALLOW_SERVICE_RESTART="${STATEBUS_CONTEST_ALLOW_SERVICE_RESTART:-0}"
  export STATEBUS_CONTEST_ALLOW_OPENEULER_VALIDATION="${STATEBUS_CONTEST_ALLOW_OPENEULER_VALIDATION:-0}"

  export STATEBUS_DOCKER_TARGET="${STATEBUS_DOCKER_TARGET:-core}"
  export STATEBUS_UID="${STATEBUS_UID:-$(id -u)}"
  export STATEBUS_GID="${STATEBUS_GID:-$(id -g)}"
  export STATEBUS_OPENEULER_RELEASE="${STATEBUS_OPENEULER_RELEASE:-24.03-lts-sp3}"
  export STATEBUS_OPENEULER_COMPOSE_FILE="${STATEBUS_OPENEULER_COMPOSE_FILE:-$repo_root/docker/compose.yaml}"
  export STATEBUS_OPENEULER_IMAGE="${STATEBUS_OPENEULER_IMAGE:-statebus-dev-openeuler:24.03-lts-sp3-core}"
  export STATEBUS_OPENEULER_VALIDATION_ROOT="${STATEBUS_OPENEULER_VALIDATION_ROOT:-$STATEBUS_CONTEST_RUN_ROOT/openeuler-final}"
  export STATEBUS_OPENEULER_VALIDATION_STATUS="${STATEBUS_OPENEULER_VALIDATION_STATUS:-pending}"

  mkdir -p \
    "$STATEBUS_CACHES_DIR" \
    "$STATEBUS_CONTEST_DATA_ROOT" \
    "$STATEBUS_CONTEST_RUN_ROOT" \
    "$STATEBUS_CONTEST_LOG_ROOT" \
    "$STATEBUS_FILING_DOWNLOAD_ROOT" \
    "$STATEBUS_FILING_CANONICAL_ROOT" \
    "$STATEBUS_FILING_PRIVATE_GOLD_ROOT" \
    "$STATEBUS_OPENEULER_VALIDATION_ROOT"

  export PYTHONPATH="$repo_root${PYTHONPATH:+:$PYTHONPATH}"

  echo "[statebus-contest] profile=$STATEBUS_CONTEST_PROFILE"
  echo "[statebus-contest] phase=$STATEBUS_CONTEST_PROFILE_PHASE"
  echo "[statebus-contest] llm_config=$STATEBUS_LLM_CONFIG_FILE"
  echo "[statebus-contest] base_url=$STATEBUS_LOCAL_VLLM_BASE_URL"
  echo "[statebus-contest] metrics_url=$STATEBUS_VLLM_METRICS_URL"
  echo "[statebus-contest] model_path=$STATEBUS_VLLM_MODEL_PATH"
  echo "[statebus-contest] run_root=$STATEBUS_CONTEST_RUN_ROOT"
  echo "[statebus-contest] policies=prefix:$STATEBUS_PREFIX_POLICY logit:$STATEBUS_LOGIT_POLICY latent:$STATEBUS_LATENT_MODE"
  echo "[statebus-contest] live actions remain disabled until separately authorized"
}

_STATEBUS_CONTEST_HAD_ERREXIT=0
_STATEBUS_CONTEST_HAD_NOUNSET=0
_STATEBUS_CONTEST_HAD_PIPEFAIL=0
if shopt -qo errexit; then
  _STATEBUS_CONTEST_HAD_ERREXIT=1
fi
if shopt -qo nounset; then
  _STATEBUS_CONTEST_HAD_NOUNSET=1
fi
if shopt -qo pipefail; then
  _STATEBUS_CONTEST_HAD_PIPEFAIL=1
fi

if _statebus_activate_contest_rebuild_main; then
  _statebus_contest_status=0
else
  _statebus_contest_status=$?
fi

_statebus_contest_restore_shell_options

unset -f _statebus_contest_restore_shell_options
unset -f _statebus_activate_contest_rebuild_main
unset _STATEBUS_CONTEST_HAD_ERREXIT _STATEBUS_CONTEST_HAD_NOUNSET _STATEBUS_CONTEST_HAD_PIPEFAIL

return "${_statebus_contest_status}" 2>/dev/null || exit "${_statebus_contest_status}"
