"""Agent implementations for the multi-agent research system.

4 agents: planner, retriever, executor, summarizer.
Each agent supports two modes:
  - "text": natural language passthrough (original behavior)
  - "structured": AgentMessage-based communication with action types,
    structured params/results, and non-text embedding transfer
"""

import time

from langchain_core.messages import HumanMessage, SystemMessage
from langchain_core.output_parsers import JsonOutputParser
from langgraph.store.base import BaseStore

from config import (
    ENABLE_CONTEXT_PACKETS,
    ENABLE_EMBEDDING_TRANSFER,
    ENABLE_HIDDEN_STATE_TRANSFER,
    HIDDEN_STATE_CONTEXT_TOP_K,
    HIDDEN_STATE_EVIDENCE_CHARS,
    HIDDEN_STATE_EVIDENCE_PER_DOC,
    NS_ANALYSIS,
    NS_DOCS,
    NS_PLANS,
    NS_SUMMARIES,
)
from memory import store_get, store_put, store_search
from metrics import metrics
from models import get_model
from protocol import (
    ActionType,
    build_context_packet,
    cosine_similarity,
    format_context_for_prompt,
    hash_text,
    make_document_key,
    make_message,
    select_context_packets,
    select_document_payloads,
    summarize_text,
    verify_context_packet,
)


def _get_mode(state: dict) -> str:
    """Get communication mode from state."""
    return state.get("mode", "text")


def _extract_hidden_state(response) -> dict | None:
    """Extract hidden-state metadata from a local Transformers response."""
    metadata = getattr(response, "response_metadata", None) or {}
    payload = metadata.get("hidden_state_payload")
    if isinstance(payload, dict):
        return payload
    return None


def _hidden_state_summary(payload: dict | None) -> dict:
    """Return compact metadata without copying the full vector into prompt text."""
    if not payload:
        return {"available": False}
    return {
        "available": True,
        "kind": payload.get("kind"),
        "model": payload.get("model"),
        "layer": payload.get("layer"),
        "pooling": payload.get("pooling"),
        "dims": payload.get("dims"),
        "norm": payload.get("norm"),
        "source_text_hash": payload.get("source_text_hash"),
    }


def _record_hidden_state_received(agent: str, payload: dict | None):
    """Record that an agent received a non-text hidden-state payload."""
    if not payload:
        return
    metrics.increment(f"hidden_state_received_{agent}")
    metrics.increment("hidden_state_vector_dims_received", int(payload.get("dims", 0)))


def _hidden_state_vector(payload: dict | None) -> list[float] | None:
    """Return a serialized hidden vector if present."""
    if not isinstance(payload, dict):
        return None
    vector = payload.get("vector")
    if not isinstance(vector, list):
        return None
    return vector


def _hidden_state_alignment(left: dict | None, right: dict | None) -> float | None:
    """Compare two hidden-state payloads generated by the same local model."""
    left_vector = _hidden_state_vector(left)
    right_vector = _hidden_state_vector(right)
    if not left_vector or not right_vector:
        return None
    return round(float(cosine_similarity(left_vector, right_vector)), 4)


def _hidden_guidance_from_packets(
    packets: list[dict],
    *,
    candidate_count: int,
    top_k: int,
    candidate_type: str = "context packets",
) -> dict:
    """Summarize how hidden-state ranking affected downstream context."""
    hidden_scores = []
    for packet in packets:
        components = packet.get("score_components", {}) or {}
        score = components.get("hidden_state")
        if score is not None:
            hidden_scores.append(float(score))
    if not hidden_scores:
        return {
            "used": False,
            "candidate_type": candidate_type,
            "candidate_packets": candidate_count,
            "selected_packets": len(packets),
        }
    return {
        "used": True,
        "candidate_type": candidate_type,
        "candidate_packets": candidate_count,
        "selected_packets": len(packets),
        "context_top_k": top_k,
        "skipped_packets": max(candidate_count - len(packets), 0),
        "selected_doc_keys": [packet.get("doc_key") for packet in packets],
        "avg_hidden_score": round(sum(hidden_scores) / len(hidden_scores), 4),
        "top_hidden_score": round(max(hidden_scores), 4),
    }


def _hidden_guidance_prompt(hidden_guidance: dict | None) -> str:
    """Render hidden-state guidance as compact prompt metadata."""
    if not hidden_guidance or not hidden_guidance.get("used"):
        return ""
    return (
        "\nHidden-state routing: Planner/retriever intent alignment selected "
        f"{hidden_guidance.get('selected_packets')} of "
        f"{hidden_guidance.get('candidate_packets')} "
        f"{hidden_guidance.get('candidate_type', 'context packets')}; "
        f"selected_doc_keys={hidden_guidance.get('selected_doc_keys')}; "
        f"avg_hidden_score={hidden_guidance.get('avg_hidden_score')}."
    )


def _normalize_sub_queries(query: str, sub_queries: list) -> list[str]:
    """Ensure fan-out has three distinct retrieval candidates."""
    normalized = []
    seen = set()
    for item in sub_queries or []:
        text = str(item).strip()
        if not text or len(text) < 8 or text in seen:
            continue
        seen.add(text)
        normalized.append(text)
        if len(normalized) == 3:
            return normalized

    fallback_aspects = [
        f"{query} 的核心概念和机制",
        f"{query} 的实现方式和关键组件",
        f"{query} 的性能、可靠性和应用场景",
    ]
    for text in fallback_aspects:
        if text in seen:
            continue
        normalized.append(text)
        if len(normalized) == 3:
            break
    return normalized



# ─── Planner Agent ───


def planner(state: dict, store: BaseStore) -> dict:
    """Break down a research query into structured sub-queries.

    Role: Planning
    Input: query (str)
    Output: plan (str), sub_queries (list[str])
    Memory: writes plan to Store under ("plans",)
    """
    t0 = time.perf_counter()
    mode = _get_mode(state)

    query = state["query"]
    task_group = state.get("task_group", "default")

    # Check if there's relevant prior knowledge in memory
    prior_results = store_search(store, NS_SUMMARIES, query, limit=2)
    prior_context = ""
    if prior_results:
        prior_context = "\n\n".join(
            f"[Prior knowledge from {r.key}]: {r.value.get('text', '')}"
            for r in prior_results
        )
        metrics.increment("memory_reuse_hits")

    capture_hidden = mode == "structured" and ENABLE_HIDDEN_STATE_TRANSFER
    model = get_model(
        temperature=0.5,
        capture_hidden=capture_hidden,
    )
    parser = JsonOutputParser()

    messages = [
        SystemMessage(content="""You are a research planner. Given a research query,
break it down into a structured plan with exactly 3 specific sub-queries for information retrieval.
The 3 sub-queries should cover complementary aspects so downstream hidden-state
routing can rank and prune context packets.

Return ONLY valid JSON with this exact format:
{
  "plan": "A concise research plan describing the approach",
  "sub_queries": ["sub-query 1", "sub-query 2", "sub-query 3"]
}"""),
        HumanMessage(content=f"Research query: {query}"
                     + (f"\n\nPrior context:\n{prior_context}" if prior_context else "")),
    ]

    response = model.invoke(messages)
    planner_hidden_state = _extract_hidden_state(response)
    if planner_hidden_state:
        metrics.increment("hidden_state_produced_planner")
    # Record LLM token usage
    if hasattr(response, "usage_metadata") and response.usage_metadata:
        um = response.usage_metadata
        metrics.record_tokens("planner", um.get("input_tokens", 0), um.get("output_tokens", 0))
    try:
        parsed = parser.invoke(response)
    except Exception:
        parsed = {
            "plan": f"Research plan for: {query}",
            "sub_queries": [
                f"What is {query}?",
                f"What are the key features of {query}?",
                f"What are the applications of {query}?",
            ],
        }

    plan = parsed.get("plan", "")
    sub_queries = _normalize_sub_queries(query, parsed.get("sub_queries", []))

    # Write plan to shared memory
    store_put(store, NS_PLANS, f"plan_{task_group}", {
        "text": plan,
        "sub_queries": sub_queries,
        "query": query,
        "planner_hidden_state": _hidden_state_summary(planner_hidden_state),
    })

    duration = time.perf_counter() - t0
    metrics.record_timing("node_planner", duration)

    result = {
        "plan": plan,
        "sub_queries": sub_queries,
    }
    if planner_hidden_state:
        result["planner_hidden_state"] = planner_hidden_state

    if mode == "structured":
        msg = make_message(
            source="planner", target="retriever",
            action=ActionType.PLAN,
            params={"query": query, "task_group": task_group},
            result={
                "plan": plan,
                "sub_queries": sub_queries,
                "hidden_state": _hidden_state_summary(planner_hidden_state),
            },
            task_group=task_group,
            hidden_state=planner_hidden_state,
        )
        metrics.record_message(
            source="planner", target="retriever", action="plan",
            param_chars=len(query), result_chars=len(plan) + sum(len(s) for s in sub_queries),
            has_embedding=False,
            has_hidden_state=planner_hidden_state is not None,
            hidden_state_dims=planner_hidden_state.get("dims", 0) if planner_hidden_state else 0,
        )
        result["messages"] = [msg.to_dict()]

    return result


# ─── Retriever Agent ───


def retriever(state: dict, store: BaseStore) -> dict:
    """Retrieve and synthesize information for a sub-query.

    Role: Retrieval
    Input: sub_query (str) — received via Send
    Output: documents (list[str])
    Memory: writes documents to Store under ("docs", task_group)
    """
    t0 = time.perf_counter()
    mode = _get_mode(state)

    sub_query = state.get("sub_query", state.get("query", ""))
    task_group = state.get("task_group", "default")
    planner_hidden_state = state.get("planner_hidden_state")
    _record_hidden_state_received("retriever", planner_hidden_state)

    capture_hidden = mode == "structured" and ENABLE_HIDDEN_STATE_TRANSFER
    model = get_model(temperature=0.3, capture_hidden=capture_hidden)

    messages = [
        SystemMessage(content="""You are a research retriever. Given a sub-query,
provide a comprehensive, factual response with key findings.
Return your response as plain text (3-5 paragraphs)."""),
        HumanMessage(content=f"Sub-query: {sub_query}"),
    ]

    response = model.invoke(messages)
    retriever_intent_hidden_state = _extract_hidden_state(response)
    intent_alignment = _hidden_state_alignment(planner_hidden_state, retriever_intent_hidden_state)
    if retriever_intent_hidden_state:
        metrics.increment("hidden_state_produced_retriever")
    if intent_alignment is not None:
        metrics.increment("hidden_state_alignment_scored_retriever")
    # Record LLM token usage
    if hasattr(response, "usage_metadata") and response.usage_metadata:
        um = response.usage_metadata
        metrics.record_tokens("retriever", um.get("input_tokens", 0), um.get("output_tokens", 0))
    doc_text = response.content

    # Generate embedding for the document (independent non-text state transfer).
    embedding = None
    if mode == "structured" and ENABLE_EMBEDDING_TRANSFER:
        try:
            from config import EMBEDDING_DIMS
            from memory import get_embeddings
            embedder = get_embeddings(dims=EMBEDDING_DIMS)
            embedding = embedder.embed_query(doc_text[:500])
        except Exception:
            embedding = None

    # Store document
    doc_key = make_document_key(task_group, sub_query, doc_text)
    store_put(store, NS_DOCS, doc_key, {
        "text": doc_text,
        "sub_query": sub_query,
        "task_group": task_group,
    })

    document_payload = {
        "doc_key": doc_key,
        "sub_query": sub_query,
        "text": doc_text,
        "text_hash": hash_text(doc_text),
        "original_chars": len(doc_text),
    }
    hidden_state_payload = None
    if retriever_intent_hidden_state:
        hidden_state_payload = {
            "ref_id": doc_key,
            "doc_key": doc_key,
            "source_agent": "retriever",
            "target_agent": "executor",
            "scope": "retrieval_intent",
            "sub_query": sub_query,
            "intent_alignment": intent_alignment,
            "hidden_state": retriever_intent_hidden_state,
        }
        document_payload["hidden_state_ref"] = doc_key
        document_payload["intent_alignment"] = intent_alignment

    # Search for related prior documents (memory reuse)
    related = store_search(store, NS_DOCS, sub_query, limit=3)
    related_docs = [r.value.get("text", "") for r in related if r.key != doc_key]
    if related_docs:
        metrics.increment("memory_reuse_hits")

    duration = time.perf_counter() - t0
    metrics.record_timing("node_retriever", duration)

    if mode == "structured":
        embedding_payload = None
        if embedding:
            embedding_payload = {
                "doc_key": doc_key,
                "embedding_ref": doc_key,
                "dims": len(embedding),
                "vector": embedding,
            }

        result_payload = {
            "doc_key": doc_key,
            "document_chars": len(doc_text),
            "planner_hidden_state": _hidden_state_summary(planner_hidden_state),
            "retriever_intent_hidden_state": _hidden_state_summary(retriever_intent_hidden_state),
            "intent_alignment": intent_alignment,
        }
        if hidden_state_payload:
            result_payload["hidden_state_ref"] = doc_key
        result = {"messages": []}
        result_chars = len(doc_text) + len(doc_key)

        if ENABLE_CONTEXT_PACKETS:
            metrics.increment("context_packets_enabled")
            context_packet = build_context_packet(
                doc_key=doc_key,
                sub_query=sub_query,
                doc_text=doc_text,
                task_group=task_group,
                embedding_ref=doc_key,
            )
            if hidden_state_payload:
                context_packet["hidden_state_ref"] = doc_key
                context_packet["intent_alignment"] = intent_alignment
                context_packet["retrieval_diagnostics"]["intent_alignment"] = intent_alignment
            result_payload.update({
                "summary": context_packet["summary"],
                "evidence_count": len(context_packet["evidence_spans"]),
                "query_coverage": context_packet["verification"]["query_coverage"],
                "reliable": context_packet["verification"]["reliable"],
                "original_chars": context_packet["original_chars"],
                "compressed_chars": context_packet["compressed_chars"],
                "compression_ratio": context_packet["compression_ratio"],
                "context_packets_enabled": True,
            })
            result["context_packets"] = [context_packet]
            result_chars = len(context_packet["summary"]) + len(doc_key)
            metrics.record_context_compression(
                original_chars=context_packet["original_chars"],
                compressed_chars=context_packet["compressed_chars"],
                source="retriever",
            )
        else:
            metrics.increment("context_packets_disabled")
            result_payload["context_packets_enabled"] = False
            result["documents"] = [doc_text] + related_docs[:1]
            result["document_payloads"] = [document_payload]

        msg = make_message(
            source="retriever", target="executor",
            action=ActionType.RETRIEVE,
            params={"sub_query": sub_query, "doc_key": doc_key},
            result=result_payload,
            task_group=task_group,
            embedding=embedding,
            hidden_state=planner_hidden_state,
        )
        metrics.record_message(
            source="retriever", target="executor", action="retrieve",
            param_chars=len(sub_query) + len(doc_key),
            result_chars=result_chars,
            has_embedding=embedding is not None,
            embedding_dims=len(embedding) if embedding else 0,
            has_hidden_state=planner_hidden_state is not None,
            hidden_state_dims=planner_hidden_state.get("dims", 0) if planner_hidden_state else 0,
        )
        result["messages"] = [msg.to_dict()]
        if embedding_payload:
            result["embedding_payloads"] = [embedding_payload]
        if hidden_state_payload:
            result["hidden_state_payloads"] = [hidden_state_payload]
            metrics.increment("hidden_state_payloads_sent")
        return result

    return {
        "documents": [doc_text] + related_docs[:1],
    }


# ─── Executor Agent ───


def executor(state: dict, store: BaseStore) -> dict:
    """Analyze retrieved context and produce structured analysis.

    Text mode consumes full documents. Structured mode consumes compact context
    packets selected by the protocol using lexical and vector scores.
    """
    t0 = time.perf_counter()
    mode = _get_mode(state)

    query = state.get("query", "")
    plan = state.get("plan", "")
    documents = state.get("documents", [])
    document_payloads = state.get("document_payloads", [])
    context_packets = state.get("context_packets", [])
    embedding_payloads = state.get("embedding_payloads", [])
    hidden_state_payloads = state.get("hidden_state_payloads", [])
    task_group = state.get("task_group", "default")
    planner_hidden_state = state.get("planner_hidden_state")
    _record_hidden_state_received("executor", planner_hidden_state)

    use_embeddings = mode == "structured" and ENABLE_EMBEDDING_TRANSFER and bool(embedding_payloads)
    if use_embeddings:
        metrics.increment("embedding_received", len(embedding_payloads))
    if hidden_state_payloads and mode == "structured":
        metrics.increment("hidden_state_payloads_received", len(hidden_state_payloads))

    # Search for prior analyses (memory reuse)
    prior_analyses = store_search(store, NS_ANALYSIS, plan, limit=2)
    prior_context = ""
    if prior_analyses:
        prior_context = "\n\n".join(
            f"[Prior analysis {r.key}]: {summarize_text(r.value.get('text', ''), 360)}"
            for r in prior_analyses
        )
        metrics.increment("memory_reuse_hits")

    selected_packets = []
    verified_packets = []
    selected_documents = []
    verification_summary = {
        "checked": 0,
        "reliable": 0,
        "rehydrated": 0,
        "failed": 0,
        "missing_docs": [],
    }
    candidate_count = len(context_packets) if context_packets else len(document_payloads or documents)
    hidden_guidance = {"used": False, "candidate_packets": candidate_count, "selected_packets": 0}
    query_text = f"{query}\n{plan}"
    query_embedding = None
    if use_embeddings:
        try:
            from config import EMBEDDING_DIMS
            from memory import get_embeddings
            embedder = get_embeddings(dims=EMBEDDING_DIMS)
            query_embedding = embedder.embed_query(query_text[:500])
        except Exception:
            query_embedding = None

    use_context_packets = mode == "structured" and ENABLE_CONTEXT_PACKETS and bool(context_packets)
    if use_context_packets:
        selected_packets = select_context_packets(
            packets=context_packets,
            query_text=query_text,
            query_embedding=query_embedding,
            embedding_payloads=embedding_payloads if use_embeddings else None,
            hidden_state_payloads=hidden_state_payloads,
            planner_hidden_state=planner_hidden_state,
            top_k=HIDDEN_STATE_CONTEXT_TOP_K if planner_hidden_state else 3,
        )
        hidden_guidance = _hidden_guidance_from_packets(
            selected_packets,
            candidate_count=len(context_packets),
            top_k=HIDDEN_STATE_CONTEXT_TOP_K if planner_hidden_state else 3,
        )
        if hidden_guidance.get("used"):
            metrics.increment("hidden_state_used_executor_context_ranking")
            metrics.increment("hidden_state_context_packets_skipped", hidden_guidance["skipped_packets"])
            selected_doc_keys = set(hidden_guidance.get("selected_doc_keys", []))
            skipped_chars = sum(
                packet.get("original_chars", 0)
                for packet in context_packets
                if packet.get("doc_key") not in selected_doc_keys
            )
            metrics.increment("hidden_state_context_chars_skipped", skipped_chars)
            hidden_guidance["skipped_original_chars"] = skipped_chars
        verified_packets, verification_summary = _verify_and_rehydrate_packets(
            selected_packets,
            store=store,
            query_text=query_text,
        )
        metrics.increment("context_packets_checked", verification_summary["checked"])
        metrics.increment("context_packets_reliable", verification_summary["reliable"])
        metrics.increment("context_packets_rehydrated", verification_summary["rehydrated"])
        metrics.increment("context_packets_failed", verification_summary["failed"])
        if hidden_guidance.get("used"):
            docs_text = format_context_for_prompt(
                verified_packets,
                evidence_per_doc=HIDDEN_STATE_EVIDENCE_PER_DOC,
                max_evidence_chars=HIDDEN_STATE_EVIDENCE_CHARS,
            )
        else:
            docs_text = format_context_for_prompt(verified_packets)
        original_chars = sum(p.get("original_chars", 0) for p in selected_packets)
        compressed_chars = len(docs_text)
        if original_chars:
            metrics.record_context_compression(
                original_chars=original_chars,
                compressed_chars=compressed_chars,
                source="executor_prompt",
            )
        context_label = "Verified compact context packets"
    else:
        if mode == "structured":
            metrics.increment("context_packet_fallback_documents")
            selected_documents = select_document_payloads(
                documents=documents,
                document_payloads=document_payloads,
                query_text=query_text,
                query_embedding=query_embedding,
                embedding_payloads=embedding_payloads if use_embeddings else None,
                hidden_state_payloads=hidden_state_payloads,
                planner_hidden_state=planner_hidden_state,
                top_k=HIDDEN_STATE_CONTEXT_TOP_K if planner_hidden_state else 3,
            )
            if selected_documents:
                docs_text = "\n---\n".join(doc.get("text", "") for doc in selected_documents)
                hidden_guidance = _hidden_guidance_from_packets(
                    selected_documents,
                    candidate_count=len(document_payloads or documents),
                    top_k=HIDDEN_STATE_CONTEXT_TOP_K if planner_hidden_state else 3,
                    candidate_type="documents",
                )
                if hidden_guidance.get("used"):
                    metrics.increment("hidden_state_used_executor_context_ranking")
                    metrics.increment("hidden_state_context_packets_skipped", hidden_guidance["skipped_packets"])
                    selected_doc_keys = set(hidden_guidance.get("selected_doc_keys", []))
                    skipped_chars = sum(
                        doc.get("original_chars", 0)
                        for doc in (document_payloads or selected_documents)
                        if doc.get("doc_key") not in selected_doc_keys
                    )
                    metrics.increment("hidden_state_context_chars_skipped", skipped_chars)
                    hidden_guidance["skipped_original_chars"] = skipped_chars
            else:
                docs_text = "\n---\n".join(documents) if documents else "No documents available."
            context_label = "Ranked documents" if selected_documents else "Documents"
        else:
            docs_text = "\n---\n".join(documents) if documents else "No documents available."
            context_label = "Documents"

    model = get_model(temperature=0.4)
    parser = JsonOutputParser()

    messages = [
        SystemMessage(content="""You are a research executor. Given a research plan
and selected context, produce a structured analysis. Use only evidence marked reliable
or rehydrated from Store. Cite `doc_key#span_id` for each claim. If coverage is
insufficient, explicitly state the limitation instead of guessing.
The evidence list contains extractive source spans in `[doc_key#span_id] text` format.

Return ONLY valid JSON:
{
  "analysis": "A comprehensive analysis paragraph",
  "evidence": [
    {"claim": "Key claim 1", "support": "Supporting evidence", "doc_key": "doc id", "span_id": "ev1"},
    {"claim": "Key claim 2", "support": "Supporting evidence", "doc_key": "doc id", "span_id": "ev2"}
  ],
  "confidence": 0.85
}"""),
        HumanMessage(content=f"Plan: {plan}{_hidden_guidance_prompt(hidden_guidance)}\n\n{context_label}:\n{docs_text}"
                     + (f"\n\nPrior analyses:\n{prior_context}" if prior_context else "")),
    ]

    response = model.invoke(messages)
    if hasattr(response, "usage_metadata") and response.usage_metadata:
        um = response.usage_metadata
        metrics.record_tokens("executor", um.get("input_tokens", 0), um.get("output_tokens", 0))
    try:
        parsed = parser.invoke(response)
    except Exception:
        parsed = {
            "analysis": f"Analysis based on: {plan}",
            "evidence": [{"claim": "Key finding", "support": "From selected context"}],
            "confidence": 0.7,
        }

    analysis = parsed.get("analysis", "")
    evidence = parsed.get("evidence", [])
    analysis_digest = summarize_text(analysis, 520)
    selected_doc_keys = [
        item.get("doc_key")
        for item in (verified_packets if verified_packets else selected_documents)
    ]

    store_put(store, NS_ANALYSIS, f"analysis_{task_group}", {
        "text": analysis,
        "digest": analysis_digest,
        "evidence": evidence,
        "plan": plan,
        "selected_doc_keys": selected_doc_keys,
        "context_verification": verification_summary,
        "hidden_guidance": hidden_guidance,
        "planner_hidden_state": _hidden_state_summary(planner_hidden_state),
    })

    duration = time.perf_counter() - t0
    metrics.record_timing("node_executor", duration)

    result = {
        "analysis": analysis,
        "analysis_digest": analysis_digest,
        "evidence": evidence,
        "hidden_guidance": hidden_guidance,
    }
    if planner_hidden_state:
        result["planner_hidden_state"] = planner_hidden_state

    if mode == "structured":
        msg = make_message(
            source="executor", target="summarizer",
            action=ActionType.ANALYZE,
            params={
                "plan": plan,
                "selected_doc_keys": selected_doc_keys,
                "context_packet_count": len(context_packets),
                "verified_packet_count": len(verified_packets),
                "planner_hidden_state": _hidden_state_summary(planner_hidden_state),
                "hidden_guidance": hidden_guidance,
            },
            result={
                "analysis_digest": analysis_digest,
                "analysis_chars": len(analysis),
                "evidence_count": len(evidence),
                "context_reliable": verification_summary["reliable"],
                "context_rehydrated": verification_summary["rehydrated"],
                "hidden_state_used": hidden_guidance.get("used", False),
            },
            task_group=task_group,
            hidden_state=planner_hidden_state,
        )
        metrics.record_message(
            source="executor", target="summarizer", action="analyze",
            param_chars=len(plan) + sum(len(str(doc_key)) for doc_key in selected_doc_keys),
            result_chars=len(analysis_digest) + len(str(len(evidence))),
            has_embedding=False,
            has_hidden_state=planner_hidden_state is not None,
            hidden_state_dims=planner_hidden_state.get("dims", 0) if planner_hidden_state else 0,
        )
        result["messages"] = [msg.to_dict()]
        result["selected_context_packets"] = verified_packets
        if selected_documents:
            result["selected_documents"] = [
                {key: doc.get(key) for key in ("doc_key", "score", "score_components", "original_chars")}
                for doc in selected_documents
            ]
        result["context_verification"] = verification_summary
        result["hidden_guidance"] = hidden_guidance

    return result


def _verify_and_rehydrate_packets(
    packets: list[dict],
    *,
    store: BaseStore,
    query_text: str,
) -> tuple[list[dict], dict]:
    """Verify packet refs against Store and add fallback evidence when needed."""
    verified_packets = []
    summary = {
        "checked": 0,
        "reliable": 0,
        "rehydrated": 0,
        "failed": 0,
        "missing_docs": [],
    }

    for packet in packets:
        summary["checked"] += 1
        doc_key = packet.get("doc_key", "")
        doc_item = store_get(store, NS_DOCS, doc_key) if doc_key else None
        if doc_item is None:
            failed_packet = dict(packet)
            failed_packet["verification"] = {
                "reliable": False,
                "requires_full_doc_lookup": True,
                "reason": "missing_full_document",
            }
            verified_packets.append(failed_packet)
            summary["failed"] += 1
            summary["missing_docs"].append(doc_key)
            continue

        doc_text = doc_item.value.get("text", "")
        enriched_packet = dict(packet)
        verification = verify_context_packet(
            enriched_packet,
            doc_text,
            query_text=query_text,
        )
        enriched_packet["verification"] = verification

        if verification["reliable"]:
            summary["reliable"] += 1
            verified_packets.append(enriched_packet)
            continue

        rehydrated_packet = _rehydrate_packet_from_store(enriched_packet, doc_text)
        summary["rehydrated"] += 1
        verified_packets.append(rehydrated_packet)

    return verified_packets, summary


def _rehydrate_packet_from_store(packet: dict, doc_text: str) -> dict:
    """Attach a bounded full-document fallback when compact evidence is insufficient."""
    rehydrated = dict(packet)
    fallback_chars = 360
    fallback_source = doc_text[:fallback_chars]
    fallback_text = summarize_text(fallback_source, fallback_chars)
    fallback_ref = {
        "doc_key": packet.get("doc_key"),
        "char_start": 0,
        "char_end": len(fallback_source),
        "text_hash": hash_text(fallback_text),
    }
    rehydrated["evidence_spans"] = list(packet.get("evidence_spans", [])) + [{
        "span_id": "rehydrated_full_doc_head",
        "text": fallback_text,
        "score": 0.0,
        "matched_terms": [],
        "source_ref": fallback_ref,
        "retrieval_method": "store_rehydration",
    }]
    rehydrated["summary"] = (
        f"{packet.get('summary', '')}\n"
        "Fallback from Store because compact evidence did not pass verification: "
        f"{fallback_text}"
    ).strip()
    rehydrated["verification"] = dict(packet.get("verification", {}), rehydrated=True)
    return rehydrated

# ─── Summarizer Agent ───


def summarizer(state: dict, store: BaseStore) -> dict:
    """Produce a final summary with key findings.

    Structured mode reads the executor digest instead of the full analysis when
    constructing the summarizer prompt.
    """
    t0 = time.perf_counter()
    mode = _get_mode(state)

    query = state.get("query", "")
    plan = state.get("plan", "")
    analysis = state.get("analysis", "")
    analysis_digest = state.get("analysis_digest", "")
    evidence = state.get("evidence", [])
    hidden_guidance = state.get("hidden_guidance", {})
    task_group = state.get("task_group", "default")
    planner_hidden_state = state.get("planner_hidden_state")
    _record_hidden_state_received("summarizer", planner_hidden_state)

    model = get_model(temperature=0.5)
    parser = JsonOutputParser()

    evidence_text = "\n".join(
        f"- {e.get('claim', '')}: {e.get('support', '')}"
        + (f" [{e.get('doc_key')}]" if e.get("doc_key") else "")
        for e in evidence
    ) if evidence else "No evidence available."
    analysis_for_prompt = analysis_digest if mode == "structured" and analysis_digest else analysis

    messages = [
        SystemMessage(content="""You are a research summarizer. Given all the
research materials, produce a clear final summary.

Return ONLY valid JSON:
{
  "summary": "A concise executive summary (3-5 paragraphs)",
  "key_findings": ["Finding 1", "Finding 2", "Finding 3"],
  "recommendations": ["Recommendation 1", "Recommendation 2"]
}"""),
        HumanMessage(content=f"""Original query: {query}
Research plan: {plan}{_hidden_guidance_prompt(hidden_guidance)}
Analysis: {analysis_for_prompt}
Evidence:
{evidence_text}"""),
    ]

    response = model.invoke(messages)
    if hasattr(response, "usage_metadata") and response.usage_metadata:
        um = response.usage_metadata
        metrics.record_tokens("summarizer", um.get("input_tokens", 0), um.get("output_tokens", 0))
    try:
        parsed = parser.invoke(response)
    except Exception:
        parsed = {
            "summary": f"Summary of research on: {query}",
            "key_findings": ["Key finding from the research"],
            "recommendations": ["Further investigation recommended"],
        }

    summary = parsed.get("summary", "")
    key_findings = parsed.get("key_findings", [])
    recommendations = parsed.get("recommendations", [])

    store_put(store, NS_SUMMARIES, f"summary_{task_group}", {
        "text": summary,
        "key_findings": key_findings,
        "recommendations": recommendations,
        "query": query,
        "planner_hidden_state": _hidden_state_summary(planner_hidden_state),
        "hidden_guidance": hidden_guidance,
    })

    duration = time.perf_counter() - t0
    metrics.record_timing("node_summarizer", duration)

    result = {
        "summary": summary,
        "key_findings": key_findings,
    }
    if planner_hidden_state:
        result["planner_hidden_state_summary"] = _hidden_state_summary(planner_hidden_state)
    if hidden_guidance.get("used"):
        metrics.increment("hidden_state_used_summarizer_guidance")
        result["hidden_guidance"] = hidden_guidance

    if mode == "structured":
        msg = make_message(
            source="summarizer", target="output",
            action=ActionType.SUMMARIZE,
            params={
                "analysis_chars": len(analysis_for_prompt),
                "evidence_count": len(evidence),
                "planner_hidden_state": _hidden_state_summary(planner_hidden_state),
                "hidden_guidance": hidden_guidance,
            },
            result={
                "summary_chars": len(summary),
                "finding_count": len(key_findings),
                "hidden_state_used": hidden_guidance.get("used", False),
            },
            task_group=task_group,
            hidden_state=planner_hidden_state,
        )
        metrics.record_message(
            source="summarizer", target="output", action="summarize",
            param_chars=len(analysis_for_prompt), result_chars=len(summary),
            has_embedding=False,
            has_hidden_state=planner_hidden_state is not None,
            hidden_state_dims=planner_hidden_state.get("dims", 0) if planner_hidden_state else 0,
        )
        result["messages"] = [msg.to_dict()]

    return result
